repos:
-   repo: https://github.com/google/yapf
    rev: 0.40.2
    hooks: 3e6cd99b6652cd00867b86e5e82a1dbccc5c0f72
    -   id: yapf
        args: ['--style=.plt_configs/.style.yapf', '--parallel', '--in-place']